# RE2 Compliance Platform — Build & Test Pipeline
# Triggers on every push to main. Produces deployment artifacts.

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  solution: 'RE2.sln'
  apiProject: 'src/RE2.ComplianceApi/RE2.ComplianceApi.csproj'
  webProject: 'src/RE2.ComplianceWeb/RE2.ComplianceWeb.csproj'
  functionsProject: 'src/RE2.ComplianceFunctions/RE2.ComplianceFunctions.csproj'

stages:
- stage: Build
  displayName: 'Build & Test'
  jobs:
  - job: BuildAndTest
    displayName: 'Restore, Build, Test, Publish'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - script: |
        set -e
        for proj in \
          tests/RE2.ComplianceApi.Tests/RE2.ComplianceApi.Tests.csproj \
          tests/RE2.ComplianceCore.Tests/RE2.ComplianceCore.Tests.csproj \
          tests/RE2.ComplianceFunctions.Tests/RE2.ComplianceFunctions.Tests.csproj \
          tests/RE2.Contract.Tests/RE2.Contract.Tests.csproj \
          tests/RE2.DataAccess.Tests/RE2.DataAccess.Tests.csproj; do
          echo "========== Testing: $proj =========="
          dotnet test "$proj" --configuration $(buildConfiguration) --logger "trx" --results-directory $(Agent.TempDirectory)/TestResults --verbosity normal
          echo "========== Done: $proj =========="
        done
      displayName: 'Run tests'
      timeoutInMinutes: 10

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
        mergeTestResults: true

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish code coverage'
      condition: succeededOrFailed()
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'

    # Publish API artifact
    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(apiProject)'
        arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/api'
        zipAfterPublish: true

    # Publish Web artifact
    - task: DotNetCoreCLI@2
      displayName: 'Publish Web'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(webProject)'
        arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/web'
        zipAfterPublish: true

    # Publish Functions artifact
    - task: DotNetCoreCLI@2
      displayName: 'Publish Functions'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(functionsProject)'
        arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/functions'
        zipAfterPublish: true

    # Copy Bicep templates as artifact
    - task: CopyFiles@2
      displayName: 'Copy Bicep templates'
      inputs:
        sourceFolder: 'infra/bicep'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/infra'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: 'drop'
      displayName: 'Publish pipeline artifacts'
