# RE2 Compliance Platform — Deploy to Dev
# Triggered automatically after successful build on main.
#
# Prerequisites:
#   Service Connection: RE2-Dev-ServiceConnection
#   Variable Group:     re2-dev-secrets (AzureAdTenantId, AzureAdClientId)
#   Environment:        re2-dev (no approval gate)

trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'RE2.1-Build'
    trigger:
      branches:
        include:
          - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: re2-dev-secrets

stages:
- stage: DeployDev
  displayName: 'Deploy to Dev'
  jobs:
  - deployment: DeployInfra
    displayName: 'Deploy infrastructure'
    environment: 're2-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Create resource group'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create \
                  --name rg-re2-dev \
                  --location westeurope \
                  --tags environment=dev application=re2-compliance

          - task: AzureCLI@2
            displayName: 'Deploy Bicep templates'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create \
                  --resource-group rg-re2-dev \
                  --template-file $(Pipeline.Workspace)/build/drop/infra/main.bicep \
                  --parameters $(Pipeline.Workspace)/build/drop/infra/dev.bicepparam \
                  --parameters azureAdTenantId=$(AzureAdTenantId) \
                               azureAdClientId=$(AzureAdClientId) \
                  --verbose

  - deployment: DeployApps
    displayName: 'Deploy applications'
    dependsOn: DeployInfra
    environment: 're2-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy API'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              appType: 'webApp'
              appName: 'app-re2-api-dev'
              package: '$(Pipeline.Workspace)/build/drop/api/**/*.zip'

          - task: AzureWebApp@1
            displayName: 'Deploy Web'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              appType: 'webApp'
              appName: 'app-re2-web-dev'
              package: '$(Pipeline.Workspace)/build/drop/web/**/*.zip'

          - task: AzureFunctionApp@2
            displayName: 'Deploy Functions'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              appType: 'functionApp'
              appName: 'func-re2-compliance-dev'
              package: '$(Pipeline.Workspace)/build/drop/functions/**/*.zip'

          - task: AzureCLI@2
            displayName: 'Smoke test — API health'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                API_URL="https://app-re2-api-dev.azurewebsites.net/health"
                echo "Testing $API_URL"
                for i in {1..6}; do
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL" --max-time 10)
                  if [ "$STATUS" = "200" ]; then
                    echo "Health check passed (HTTP 200)"
                    exit 0
                  fi
                  echo "Attempt $i: HTTP $STATUS — retrying in 10s..."
                  sleep 10
                done
                echo "Health check FAILED after 6 attempts"
                exit 1

          - task: AzureCLI@2
            displayName: 'Smoke test — Web health'
            inputs:
              azureSubscription: 'RE2-Dev-ServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                WEB_URL="https://app-re2-web-dev.azurewebsites.net/health"
                echo "Testing $WEB_URL"
                for i in {1..6}; do
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WEB_URL" --max-time 10)
                  if [ "$STATUS" = "200" ]; then
                    echo "Health check passed (HTTP 200)"
                    exit 0
                  fi
                  echo "Attempt $i: HTTP $STATUS — retrying in 10s..."
                  sleep 10
                done
                echo "Health check FAILED after 6 attempts"
                exit 1
